""" 2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 3 and 4,
    the first 10 terms of the Fibonacci-like sequence will be: 3, 4, 7, 11, 18, 29, 47, 76, 123, 199, ... .
    By considering the terms in this sequence whose values do not exceed seven million, find the sum of the even-valued
    terms.
"""

fibonacci_numbers = [3, 4]
list_endpoint = 7000000

while fibonacci_numbers[-1] <= 7000000:
    last_namber = fibonacci_numbers[-2] + fibonacci_numbers[-1]
    if last_namber > list_endpoint:
        break
    fibonacci_numbers.append(last_namber)

sum_even_numbers = sum([x for x in fibonacci_numbers if x % 2 == 0])

print(fibonacci_numbers)
print(sum_even_numbers)
